<?php

return [
    'earrings' => [
        [
            "name" => "Pane & Barattolo Nutella Pendant Earrings",
            "code" => 17,
            "price" => 7.00,
            "description" => "Pane e Barattolo Nutella Pendant earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini-nutella-e-fetta.jpg",
        ],
        [
            "name" => "Sushi & Onigiri Pendant Earrings",
            "code" => 32,
            "price" => 6.50,
            "description" => "Sushi & Onigiri Pendant earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini-sushi-e-onigiri.jpg",
        ],
        [
            "name" => "Hot Chocolate Pendant Earrings",
            "code" => "229",
            "price" => 7.50,
            "description" => "Hot chocolate Pendant earrings, nichel free, handmade with ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20hot%20chocolate.jpg",
        ],
        [
            "name" => "Red Chocolate Pendant Earrings",
            "code" => "453",
            "price" => 7.50,
            "description" => "Hot chocolate Pendant earrings, nichel free, handmade with decorated ceramic components ",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20red%20chocolate.jpg",
        ],
        [
            "name" => "Pan di Stelle Pin Earrings",
            "code" => 250,
            "price" => 5.00,
            "description" => "Pan di Stelle biscuits Pin earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20choco-breakfast.jpg",
        ],
        [
            "name" => "Choco-Breakfast Pendant Earrings",
            "code" => 241,
            "price" => 7.50,
            "description" => "Choco-Breakfast Pendant earrings, nichel free, handmade whith ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20choco-breakfast.jpg",
        ],
        [
            "name" => "Chupa-Chups Pendant Earrings",
            "code" => 340,
            "price" => 6.80,
            "description" => "Chupa-Chups Pendant earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20chupa%20chups.jpg",
        ],
        [
            "name" => "Hot Chocolate Pin Earrings",
            "code" => 341,
            "price" => 6.00,
            "description" => "Hot chocolate Pin earrings, nichel free, handmade with ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20vite%20hot%20chocolate.jpg",
        ],
        [
            "name" => "Vintage Tea Pendant Earrings",
            "code" => 376,
            "price" => 12.00,
            "description" => "Vintage Tea Pendant Earrings, nichel free, handmade with a cabochon base",
            "img" => "http://funnyfimo.altervista.org/orecchini/vintage%20tea.jpg",
        ],
        [
            "name" => "Ice Cream Biscuits Pendant Earrings",
            "code" => 348,
            "price" => 7.00,
            "description" => "Ice Cream Biscuits Pendant Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20gelato%20biscotto.jpg",
        ],
        [
            "name" => "Ramen Pendant Earrings",
            "code" => 430,
            "price" => 12.00,
            "description" => "Ramen Pendant Earrings, nichel free, handmade with ceramic and wood components",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20ramen.jpg",
        ],
        [
            "name" => "Pinwheel Pendant Earrings",
            "code" => 505,
            "price" => 6.00,
            "description" => "Pinwheel Pendant Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20girandola.jpg",
        ],
        [
            "name" => "Parfum Pendant Earrings",
            "code" => 506,
            "price" => 6.50,
            "description" => "Parfum Pendant Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20parfum.jpg",
        ],
        [
            "name" => "Ramen Clip Earrings",
            "code" => 534,
            "price" => 5.00,
            "description" => "Ramen Clip Earrings, nichel free, handmade with ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20ramen%20clip.jpg",
        ],
        [
            "name" => "Cupcake Pin Earrings",
            "code" => 543,
            "price" => 5.00,
            "description" => "Cupcake Pin Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20vite%20cupcake.jpg",
        ],
        [
            "name" => "Crepes Pin Earrings",
            "code" => 546,
            "price" => 5.00,
            "description" => "Crepes Pin Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20vite%20crepe.jpg",
        ],
        [
            "name" => "Kinder Cereali Pin Earrings",
            "code" => 545,
            "price" => 5.00,
            "description" => "Kinder Cereali Pin Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20kinder%20cereali.jpg",
        ],
        [
            "name" => "Baci Pin Earrings",
            "code" => 550,
            "price" => 7.00,
            "description" => "Baci Pin Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/bacivite.jpg",
        ],
        [
            "name" => "Baci Pendant Earrings",
            "code" => 550,
            "price" => 7.00,
            "description" => "Baci Pendant Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20baci%20piccoli.jpg",
        ],
        [
            "name" => "French Macaron Pendant Earrings",
            "code" => 543,
            "price" => 7.00,
            "description" => "French Macaron Pendant Earrings, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20french%20macaron.jpg",
        ],
        ]
];