<?php

return [
    'rings' => [
        [
            "name" => "Nutella adjustable ring",
            "code" => 167,
            "price" => 5.50,
            "description" => "Pane e Barattolo Nutella ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20nutella.jpg",
        ],
        [
            "name" => "Sushi mix adjustable ring",
            "code" => 168,
            "price" => 6.00,
            "description" => "Sushi mix ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20sushi%20misto.jpg",
        ],
        [
            "name" => "Biscuits & Donuts large plate adjustable ring",
            "code" => 202,
            "price" => 8.00,
            "description" => "Biscuits & Donuts large plate ring, nichel free, handmade with ceramic components, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20piatto%20biscotti%20e%20ciambelle.jpg",
        ],
        [
            "name" => "Biscuits & Donuts small plate adjustable ring",
            "code" => 253,
            "price" => 7.00,
            "description" => "Biscuits & Donuts small plate ring, nichel free, handmade with ceramic components, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20piatto%20biscotti%20e%20ciambelle%20piccolo.jpg",
        ],
        [
            "name" => "Candyfloss adjustable ring",
            "code" => 224,
            "price" => 5.50,
            "description" => "Candyfloss ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20zucchero%20filato%20rosa.jpg",
        ],
        [
            "name" => "Hot Chocolate adjustable ring",
            "code" => 228,
            "price" => 5.50,
            "description" => "Hot Chocolate ring, handmade whith ceramic components, all sizes, 5 colors available",
            "img" => "http://funnyfimo.altervista.org/orecchini/anelli%20tazzina%20semplice1.jpg",
        ],
        [
            "name" => "Tart adjustable ring",
            "code" => 257,
            "price" => 6.0,
            "description" => "Tart ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20crostata.jpg",
        ],
        [
            "name" => "Doily Hot Chocolate adjustable ring",
            "code" => 305,
            "price" => 7.300,
            "description" => "Doily Hot Chocolate ring, nichel free, handmade with ceramic components, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20vite%20hot%20chocolate.jpg",
        ],
        [
            "name" => "Lemon Tea adjustable ring",
            "code" => 316,
            "price" => 7.50,
            "description" => "Lemon Tea ring, nichel free, handmade with ceramic components, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20Lemon%20tea.jpg",
        ],
        [
            "name" => "Sushi Plate adjustable ring",
            "code" => 318,
            "price" => 8.00,
            "description" => "ISushi Plate ring, nichel free, handmade with ceramic components, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20sushi.jpg",
        ],
        [
            "name" => "KitKat adjustable ring",
            "code" => 430,
            "price" => 12.00,
            "description" => "KitKat ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20kitkat.jpg",
        ],
        [
            "name" => "Sweet Biscuit adjustable ring",
            "code" => 324,
            "price" => 7.00,
            "description" => "Sweet Biscuit ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20dolce%20biscotto.jpg",
        ],
        [
            "name" => "Marmalade Biscuit adjustable ring",
            "code" => 325,
            "price" => 7.00,
            "description" => "Marmalade Biscuit ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20canestrello%20marmellata.jpg",
        ],
        [
            "name" => "Croissant Hot Chocolate adjustable ring, Pink",
            "code" => 338,
            "price" => 7.80,
            "description" => "Croissant Hot Chocolate ring, nichel free, handmade with ceramic components, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20choco%20croissant%20pink.jpg",
        ],
        [
            "name" => "Hot Chocolate adjustable ring, Blue",
            "code" => 337,
            "price" => 7.80,
            "description" => "Croissant Hot Chocolate adjustable ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20choco%20croissant%20blue.jpg",
        ],
        [
            "name" => "IceCream adjustable ring",
            "code" => 349,
            "price" => 7.00,
            "description" => "IceCream ring, nichel free, handmade, all sizes, with ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20icecream.jpg",
        ],
        [
            "name" => "Waffle adjustable ring",
            "code" => 351,
            "price" => 7.00,
            "description" => "Waffle ring, nichel free, handmade",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20waffle.jpg",
        ],
        [
            "name" => "Chocolate Tart adjustable ring",
            "code" => 390,
            "price" => 10.00,
            "description" => "Chocolate Tart ring, nichel free, handmade, all size,s with ceramic and glass components",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20chocolate%20tart.jpg",
        ],
        [
            "name" => "Love Donuts adjustable ring",
            "code" => 413,
            "price" => 7.00,
            "description" => "Love Donuts adjustable ring, nichel free, handmade, all sizes, with ceramic and glass components",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20love%20donuts.jpg",
        ],
        [
            "name" => "Cocktail adjustable ring",
            "code" => 512,
            "price" => 8.00,
            "description" => "Cocktail ring, nichel free, handmade, all sizes, with ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/orecchini%20french%20macaron.jpg",
        ],
        [
            "name" => "Sweet Breakfast adjustable ring",
            "code" => 458,
            "price" => 8.00,
            "description" => "Sweet Breakfast ring, nichel free, handmade, all sizes, with ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/anelli%20sweet%20breakfat.jpg",
        ],
        [
            "name" => "Ramen adjustable ring",
            "code" => 429,
            "price" => 8.00,
            "description" => "Ramen ring, nichel free, handmade, all sizes, with ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20ramen.jpg",
        ],
        [
            "name" => "Choco Vintage adjustable ring",
            "code" => 421,
            "price" => 8.50,
            "description" => "Choco Vintage ring, nichel free, handmade, all sizes, with ceramic components",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20choco%20vintage.jpg",
        ],
        [
            "name" => "Pan di Stelle adjustable ring",
            "code" => 415,
            "price" => 7.50,
            "description" => "Pan di Stelle ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20pandistelle.jpg",
        ],
        [
            "name" => "Petite Dessert adjustable ring",
            "code" => 382,
            "price" => 7.80,
            "description" => "Petite Dessert ring, nichel free, handmade, all sizes",
            "img" => "http://funnyfimo.altervista.org/orecchini/anello%20petit%20dessert.jpg",
        ],
        ]
];